server:
    port: 9002
spring:
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
            #      路由策略
            routes:
                - id: kill-core
                  uri: lb://kill-core
                  predicates:
                      - Path= /kill/**
                - id: kill-shopping-cart
                  uri: lb://kill-shopping-cart
                  predicates:
                      - Path= /cart/**
                - id: kill-user
                  uri: lb://kill-user
                  predicates:
                      - Path= /user/**
        nacos:
            discovery:
                server-addr: localhost:8848
    application:
        name: kill-gate-way

#                  filters:
#                      - StripPrefix=1
management:
    endpoints:
        web:
            exposure:
                include: '*'
