server:
  port: 9001
  servlet:
    context-path: '/kill'

web:
  swagger:
    base-package-path: com.kill.core.controller
    tittle: '工具测试服务'

spring:
  profiles:
    active: prod
  application:
    name: kill-core
  mvc:
    async:
      request-timeout: 200000
  cloud:
      nacos:
          discovery:
              server-addr: localhost:8848
logging:
    level:
        org.apdplat.word: error
