spring:
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.p6spy.engine.spy.P6SpyDriver
        url: jdbc:p6spy:mysql://192.167.180.4:33061/project_manager?useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
        username: developer
        password: w&VMZ2CXJ$@*kAz^
        hikari:
            minimum-idle: 5
            idle-timeout: 600000
            maximum-pool-size: 10
            auto-commit: true
            pool-name: MyHikariCP
            max-lifetime: 1800000
            connection-timeout: 30000
            connection-test-query: SELECT 1
logback.path: /${log.path}/${spring.application.name}
