server:
  port: 9001
  servlet:
    context-path: '/kill'

web:
  swagger:
    base-package-path: com.kill.core.controller
    tittle: '工具测试服务'

spring:
  profiles:
    active: local
  application:
    name: kill-core
  mvc:
    async:
      request-timeout: 200000
#  cloud:
#      nacos:
#          discovery:
#              server-addr: localhost:8848
#dubbo:
#    scan:
#        base-packages: com.kill.core
#    protocol:
#        name: dubbo
#        port: -1
#        serialization: kryo
#    cloud:
#        subscribed-services: kill-core-service-2
#    consumer:
#        check: false
#    provider:
#        loadbalance: roundrobin
#    registry:
##        address: spring-cloud://${nacos.server}
#        address: spring-cloud://localhost:8848
# 发送his的处方
his:
    order:
        # 分钟
        delayTime: 5
logging:
    level:
        org.apdplat.word: error
