server:
  port: 9001
  servlet:
    context-path: '/kill'

web:
  swagger:
    base-package-path: com.kill.core.controller
    tittle: '秒杀核心模块'

spring:
  profiles:
    active: local
  application:
    name: kill-core
  mvc:
    async:
      request-timeout: 200000