spring:
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.p6spy.engine.spy.P6SpyDriver
        url: jdbc:p6spy:mysql://192.168.91.37:8066/train_project_center?useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
        username: mycatread
        password: mycatread2020
        hikari:
            minimum-idle: 5
            idle-timeout: 600000
            maximum-pool-size: 10
            auto-commit: true
            pool-name: MyHikariCP
            max-lifetime: 1800000
            connection-timeout: 30000
            connection-test-query: SELECT 1
logback.path: /Users/wangjian/mall_volumns/log/${spring.application.name}
