server:
  port: 9002
  servlet:
    context-path: '/kill2'

web:
  swagger:
    base-package-path: com.kill.core.controller
    tittle: '秒杀核心模块'

spring:
  profiles:
    active: local
  application:
    name: kill-core-service-2
  cloud:
      nacos:
          discovery:
              server-addr: localhost:8848
dubbo:
    scan:
        base-packages: com.kill.core.service.impl.rpc
    protocol:
        name: dubbo
        port: -1
        serialization: kryo
    cloud:
        subscribed-services: ""
    consumer:
        check: false
    provider:
        loadbalance: roundrobin
    registry:
#        address: spring-cloud://${nacos.server}
        address: spring-cloud://localhost:8848
