server:
    port: 9005
    servlet:
        context-path: /code
spring:
    profiles:
        active: local
    application:
        name: kill-code
    cloud:
        nacos:
            discovery:
                server-addr: localhost:8848
web:
    swagger:
        base-package-path: com.kill.core.controller
        tittle: '代码生成服务'
